name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 📚 Validate composer.json and composer.lock
      run: composer validate --strict

    - name: 📖 Install dependencies
      run: composer install
      
    - name: 🐳 Run containers
      run: |
        make build
        make run
    
    - name: 📔 Linter
      run: make lint
